// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tbkk.Models;

namespace tbkk.Migrations
{
    [DbContext(typeof(tbkkdbContext))]
    partial class tbkkdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tbkk.Models.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Asset_CompanyIDCompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("Asset_DepartmentIDDepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("Asset_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("Asset_LocationIDLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("Asset_ModelIDModelID")
                        .HasColumnType("int");

                    b.Property<int?>("Asset_SupplierIDSupplierID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MACAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerailNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("AssetID");

                    b.HasIndex("Asset_CompanyIDCompanyID");

                    b.HasIndex("Asset_DepartmentIDDepartmentID");

                    b.HasIndex("Asset_EmployeeIDEmployeeID");

                    b.HasIndex("Asset_LocationIDLocationID");

                    b.HasIndex("Asset_ModelIDModelID");

                    b.HasIndex("Asset_SupplierIDSupplierID");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("tbkk.Models.AssetJoinNetwork", b =>
                {
                    b.Property<int>("AssetJoinNetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetJoinNetwork_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("AssetJoinNetwork_NetworkIDNetworkID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetJoinNetworkID");

                    b.HasIndex("AssetJoinNetwork_AssetIDAssetID");

                    b.HasIndex("AssetJoinNetwork_NetworkIDNetworkID");

                    b.ToTable("AssetJoinNetworks");
                });

            modelBuilder.Entity("tbkk.Models.Asset_Cock", b =>
                {
                    b.Property<int>("Asset_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyIDCompany_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentIDDepartment_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SerailNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierIDSupplier_CockID")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Asset_CockID");

                    b.HasIndex("CompanyIDCompany_CockID");

                    b.HasIndex("DepartmentIDDepartment_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.HasIndex("SupplierIDSupplier_CockID");

                    b.ToTable("Asset_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("tbkk.Models.Canteen", b =>
                {
                    b.Property<int>("CanteenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Call")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanteenID");

                    b.ToTable("Canteen");
                });

            modelBuilder.Entity("tbkk.Models.CarQueue", b =>
                {
                    b.Property<int>("CarQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarNumber")
                        .HasColumnType("int");

                    b.Property<int>("CarQueue_CarTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CarQueue_OTID")
                        .HasColumnType("int");

                    b.Property<int>("CarQueue_PartID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarQueueID");

                    b.HasIndex("CarQueue_CarTypeID");

                    b.HasIndex("CarQueue_OTID");

                    b.HasIndex("CarQueue_PartID");

                    b.ToTable("CarQueue");
                });

            modelBuilder.Entity("tbkk.Models.CarType", b =>
                {
                    b.Property<int>("CarTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyCarID")
                        .HasColumnType("int");

                    b.Property<string>("NameCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.HasKey("CarTypeID");

                    b.HasIndex("CompanyCarID");

                    b.ToTable("CarType");
                });

            modelBuilder.Entity("tbkk.Models.CarType_Cock", b =>
                {
                    b.Property<int>("CarType_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CerNumber")
                        .HasColumnType("int");

                    b.Property<string>("NameCar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarType_CockID");

                    b.ToTable("CarType_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("tbkk.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("tbkk.Models.CompanyCar", b =>
                {
                    b.Property<int>("CompanyCarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Call")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCompanyCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyCarID");

                    b.ToTable("CompanyCar");
                });

            modelBuilder.Entity("tbkk.Models.Company_Cock", b =>
                {
                    b.Property<int>("Company_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_CockID");

                    b.ToTable("Company_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompDetaill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompSumPoint")
                        .HasColumnType("int");

                    b.Property<int?>("Competency_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("Competency_GradeHistoryIDGradeHistoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("CompetencyID");

                    b.HasIndex("Competency_EmployeeIDEmployeeID");

                    b.HasIndex("Competency_GradeHistoryIDGradeHistoryID");

                    b.ToTable("Competency");
                });

            modelBuilder.Entity("tbkk.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("tbkk.Models.Department_Cock", b =>
                {
                    b.Property<int>("Department_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Department_CockID");

                    b.ToTable("Department_Cock");
                });

            modelBuilder.Entity("tbkk.Models.DetailCarQueue", b =>
                {
                    b.Property<int>("DetailCarQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DetailCarQueue_CarQueueID")
                        .HasColumnType("int");

                    b.Property<int>("DetailCarQueue_EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("DetailCarQueueID");

                    b.HasIndex("DetailCarQueue_CarQueueID");

                    b.HasIndex("DetailCarQueue_EmployeeID");

                    b.ToTable("DetailCarQueue");
                });

            modelBuilder.Entity("tbkk.Models.DetailOT", b =>
                {
                    b.Property<int>("DetailOTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Employee_EmpID")
                        .HasColumnType("int");

                    b.Property<int>("FoodSet_FoodSetID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hour")
                        .HasColumnType("time");

                    b.Property<int>("OT_OTID")
                        .HasColumnType("int");

                    b.Property<int>("Part_PaetID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailOTID");

                    b.HasIndex("Employee_EmpID");

                    b.HasIndex("FoodSet_FoodSetID");

                    b.HasIndex("OT_OTID");

                    b.HasIndex("Part_PaetID");

                    b.ToTable("DetailOT");
                });

            modelBuilder.Entity("tbkk.Models.DetailOT_Cock", b =>
                {
                    b.Property<int>("DetailOT_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarNumber")
                        .HasColumnType("int");

                    b.Property<int?>("CarType_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("FoodSet_CockID")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int?>("OTIDOT_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("PartIDPart_CockID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailOT_CockID");

                    b.HasIndex("CarType_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.HasIndex("FoodSet_CockID");

                    b.HasIndex("OTIDOT_CockID");

                    b.HasIndex("PartIDPart_CockID");

                    b.ToTable("DetailOT_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Call")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_EmployeeTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_LocationID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_PositionID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("Employee_CompanyID");

                    b.HasIndex("Employee_DepartmentID");

                    b.HasIndex("Employee_EmployeeTypeID");

                    b.HasIndex("Employee_LocationID");

                    b.HasIndex("Employee_PositionID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("tbkk.Models.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTypeID");

                    b.ToTable("EmployeeType");
                });

            modelBuilder.Entity("tbkk.Models.EmployeeType_Cock", b =>
                {
                    b.Property<int>("EmployeeType_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeType_CockID");

                    b.ToTable("EmployeeType_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Employee_Cock", b =>
                {
                    b.Property<int>("Employee_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyIDCompany_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentNameDepartment_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeType_CockID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionIDPosition_CockID")
                        .HasColumnType("int");

                    b.HasKey("Employee_CockID");

                    b.HasIndex("CompanyIDCompany_CockID");

                    b.HasIndex("DepartmentNameDepartment_CockID");

                    b.HasIndex("EmployeeType_CockID");

                    b.HasIndex("PositionIDPosition_CockID");

                    b.ToTable("Employee_Cock");
                });

            modelBuilder.Entity("tbkk.Models.FoodSet", b =>
                {
                    b.Property<int>("FoodSetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Canteen_CanteenID")
                        .HasColumnType("int");

                    b.Property<string>("FoodSetcoManul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodSetID");

                    b.HasIndex("Canteen_CanteenID");

                    b.ToTable("FoodSet");
                });

            modelBuilder.Entity("tbkk.Models.FoodSet_Cock", b =>
                {
                    b.Property<int>("FoodSet_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodSet_CockID");

                    b.ToTable("FoodSet_Cock");
                });

            modelBuilder.Entity("tbkk.Models.GradeHistory", b =>
                {
                    b.Property<int>("GradeHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("GradeHistory_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("GrahAllPoint")
                        .HasColumnType("int");

                    b.Property<int>("GrahBonus")
                        .HasColumnType("int");

                    b.Property<int>("GrahSalaryUp")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrahYear")
                        .HasColumnType("datetime2");

                    b.HasKey("GradeHistoryID");

                    b.HasIndex("GradeHistory_EmployeeIDEmployeeID");

                    b.ToTable("GradeHistory");
                });

            modelBuilder.Entity("tbkk.Models.GradeHistory_Cock", b =>
                {
                    b.Property<int>("GradeHistory_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<int>("GrahAllPoint")
                        .HasColumnType("int");

                    b.Property<int>("GrahBonus")
                        .HasColumnType("int");

                    b.Property<int>("GrahSalaryUp")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrahYear")
                        .HasColumnType("datetime2");

                    b.HasKey("GradeHistory_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.ToTable("GradeHistory_Cock");
                });

            modelBuilder.Entity("tbkk.Models.JoinAssetEmp", b =>
                {
                    b.Property<int>("JoinAssetEmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JoinAssetEmp_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("JoinAssetEmp_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JoinAssetEmpID");

                    b.HasIndex("JoinAssetEmp_AssetIDAssetID");

                    b.HasIndex("JoinAssetEmp_EmployeeIDEmployeeID");

                    b.ToTable("JoinAssetEmp");
                });

            modelBuilder.Entity("tbkk.Models.JoinAssetEmp_Cock", b =>
                {
                    b.Property<int>("JoinAssetEmp_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetNameAsset_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JoinAssetEmp_CockID");

                    b.HasIndex("AssetNameAsset_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.ToTable("JoinAssetEmp_Cock");
                });

            modelBuilder.Entity("tbkk.Models.JoinLicenseAsset", b =>
                {
                    b.Property<int>("JoinLicenseAssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JoinLicenseAsset_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("JoinLicenseAsset_LicenseLicenseID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JoinLicenseAssetID");

                    b.HasIndex("JoinLicenseAsset_AssetIDAssetID");

                    b.HasIndex("JoinLicenseAsset_LicenseLicenseID");

                    b.ToTable("JoinLicenseAsset");
                });

            modelBuilder.Entity("tbkk.Models.KPI", b =>
                {
                    b.Property<int>("KPIID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KPIDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KPISumPoint")
                        .HasColumnType("int");

                    b.Property<int?>("KPI_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("KPI_GradeHistoryIDGradeHistoryID")
                        .HasColumnType("int");

                    b.HasKey("KPIID");

                    b.HasIndex("KPI_EmployeeIDEmployeeID");

                    b.HasIndex("KPI_GradeHistoryIDGradeHistoryID");

                    b.ToTable("KPI");
                });

            modelBuilder.Entity("tbkk.Models.License", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachfiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("License_CompanyIDCompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("License_DepartmentIDDepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("License_ModelIDModelID")
                        .HasColumnType("int");

                    b.Property<int?>("License_SupplierIDSupplierID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoftewareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseID");

                    b.HasIndex("License_CompanyIDCompanyID");

                    b.HasIndex("License_DepartmentIDDepartmentID");

                    b.HasIndex("License_ModelIDModelID");

                    b.HasIndex("License_SupplierIDSupplierID");

                    b.ToTable("License");
                });

            modelBuilder.Entity("tbkk.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("tbkk.Models.Login", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Login_EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginID");

                    b.HasIndex("Login_EmployeeID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("tbkk.Models.Model", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Model_BrandIDBrandID")
                        .HasColumnType("int");

                    b.Property<int?>("Model_CategoryIDCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ModelID");

                    b.HasIndex("Model_BrandIDBrandID");

                    b.HasIndex("Model_CategoryIDCategoryID");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("tbkk.Models.Network", b =>
                {
                    b.Property<int>("NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IpAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetworkID");

                    b.ToTable("Network");
                });

            modelBuilder.Entity("tbkk.Models.OT", b =>
                {
                    b.Property<int>("OTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("OTID");

                    b.ToTable("OT");
                });

            modelBuilder.Entity("tbkk.Models.OT_Cock", b =>
                {
                    b.Property<int>("OT_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OT_CockID");

                    b.ToTable("OT_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Part", b =>
                {
                    b.Property<int>("PartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartID");

                    b.ToTable("Part");
                });

            modelBuilder.Entity("tbkk.Models.Part_Cock", b =>
                {
                    b.Property<int>("Part_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Part_CockID");

                    b.ToTable("Part_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Point", b =>
                {
                    b.Property<int>("PointID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamePoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Point_PartIDPartID")
                        .HasColumnType("int");

                    b.HasKey("PointID");

                    b.HasIndex("Point_PartIDPartID");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("tbkk.Models.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("tbkk.Models.Position_Cock", b =>
                {
                    b.Property<int>("Position_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Position_CockID");

                    b.ToTable("Position_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Relationship", b =>
                {
                    b.Property<int>("RelationshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Relationship_AssetIDmomAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("Relationship_AssetIDsonAssetID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RelationshipID");

                    b.HasIndex("Relationship_AssetIDmomAssetID");

                    b.HasIndex("Relationship_AssetIDsonAssetID");

                    b.ToTable("Relationship");
                });

            modelBuilder.Entity("tbkk.Models.Repair", b =>
                {
                    b.Property<int>("RepairID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Repair_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("Repair_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("Repair_ReportIDReportID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepairID");

                    b.HasIndex("Repair_AssetIDAssetID");

                    b.HasIndex("Repair_EmployeeIDEmployeeID");

                    b.HasIndex("Repair_ReportIDReportID");

                    b.ToTable("Repair");
                });

            modelBuilder.Entity("tbkk.Models.Repair_Cock", b =>
                {
                    b.Property<int>("Repair_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetIDAsset_CockID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<int?>("ReportIDReport_CockID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Repair_CockID");

                    b.HasIndex("AssetIDAsset_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.HasIndex("ReportIDReport_CockID");

                    b.ToTable("Repair_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Report_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("Report_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("Report_AssetIDAssetID");

                    b.HasIndex("Report_EmployeeIDEmployeeID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("tbkk.Models.Report_Cock", b =>
                {
                    b.Property<int>("Report_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetIDAsset_CockID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeIDEmployee_CockID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Report_CockID");

                    b.HasIndex("AssetIDAsset_CockID");

                    b.HasIndex("EmployeeIDEmployee_CockID");

                    b.ToTable("Report_Cock");
                });

            modelBuilder.Entity("tbkk.Models.Suggestion", b =>
                {
                    b.Property<int>("SuggestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SugDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SugSumPoint")
                        .HasColumnType("int");

                    b.Property<int?>("Suggestion_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("Suggestion_GradeHistoryIDGradeHistoryID")
                        .HasColumnType("int");

                    b.HasKey("SuggestionID");

                    b.HasIndex("Suggestion_EmployeeIDEmployeeID");

                    b.HasIndex("Suggestion_GradeHistoryIDGradeHistoryID");

                    b.ToTable("Suggestion");
                });

            modelBuilder.Entity("tbkk.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("tbkk.Models.Supplier_Cock", b =>
                {
                    b.Property<int>("Supplier_CockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Supplier_CockID");

                    b.ToTable("Supplier_Cock");
                });

            modelBuilder.Entity("tbkk.Models.UpdateAsset", b =>
                {
                    b.Property<int>("UpdateAssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MACAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerailNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateAsset_AssetIDAssetID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_CompanyIDCompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_LocationIDLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_ModelIDModelID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_SepartmentIDDepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateAsset_SupplierIDSupplierID")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("UpdateAssetID");

                    b.HasIndex("UpdateAsset_AssetIDAssetID");

                    b.HasIndex("UpdateAsset_CompanyIDCompanyID");

                    b.HasIndex("UpdateAsset_EmployeeIDEmployeeID");

                    b.HasIndex("UpdateAsset_LocationIDLocationID");

                    b.HasIndex("UpdateAsset_ModelIDModelID");

                    b.HasIndex("UpdateAsset_SepartmentIDDepartmentID");

                    b.HasIndex("UpdateAsset_SupplierIDSupplierID");

                    b.ToTable("UpdateAsset");
                });

            modelBuilder.Entity("tbkk.Models.UpdateLicense", b =>
                {
                    b.Property<int>("UpdateLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachfiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateLicense_CompanyIDCompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateLicense_DepartmentIDDepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateLicense_LicenseIDLicenseID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateLicense_ModelIDModelID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateLicense_SupplierIDSupplierID")
                        .HasColumnType("int");

                    b.HasKey("UpdateLicenseID");

                    b.HasIndex("UpdateLicense_CompanyIDCompanyID");

                    b.HasIndex("UpdateLicense_DepartmentIDDepartmentID");

                    b.HasIndex("UpdateLicense_LicenseIDLicenseID");

                    b.HasIndex("UpdateLicense_ModelIDModelID");

                    b.HasIndex("UpdateLicense_SupplierIDSupplierID");

                    b.ToTable("UpdateLicense");
                });

            modelBuilder.Entity("tbkk.Models.UpdateNetwork", b =>
                {
                    b.Property<int>("UpdateNetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateNetwork_EmployeeIDEmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateNetwork_NetworkIDNetworkID")
                        .HasColumnType("int");

                    b.HasKey("UpdateNetworkID");

                    b.HasIndex("UpdateNetwork_EmployeeIDEmployeeID");

                    b.HasIndex("UpdateNetwork_NetworkIDNetworkID");

                    b.ToTable("UpdateNetwork");
                });

            modelBuilder.Entity("tbkk.Models.Asset", b =>
                {
                    b.HasOne("tbkk.Models.Company", "Asset_CompanyID")
                        .WithMany()
                        .HasForeignKey("Asset_CompanyIDCompanyID");

                    b.HasOne("tbkk.Models.Department", "Asset_DepartmentID")
                        .WithMany()
                        .HasForeignKey("Asset_DepartmentIDDepartmentID");

                    b.HasOne("tbkk.Models.Employee", "Asset_EmployeeID")
                        .WithMany()
                        .HasForeignKey("Asset_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.Location", "Asset_LocationID")
                        .WithMany()
                        .HasForeignKey("Asset_LocationIDLocationID");

                    b.HasOne("tbkk.Models.Model", "Asset_ModelID")
                        .WithMany()
                        .HasForeignKey("Asset_ModelIDModelID");

                    b.HasOne("tbkk.Models.Supplier", "Asset_SupplierID")
                        .WithMany()
                        .HasForeignKey("Asset_SupplierIDSupplierID");
                });

            modelBuilder.Entity("tbkk.Models.AssetJoinNetwork", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "AssetJoinNetwork_AssetID")
                        .WithMany()
                        .HasForeignKey("AssetJoinNetwork_AssetIDAssetID");

                    b.HasOne("tbkk.Models.Network", "AssetJoinNetwork_NetworkID")
                        .WithMany()
                        .HasForeignKey("AssetJoinNetwork_NetworkIDNetworkID");
                });

            modelBuilder.Entity("tbkk.Models.Asset_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Company_Cock", "CompanyID")
                        .WithMany()
                        .HasForeignKey("CompanyIDCompany_CockID");

                    b.HasOne("tbkk.Models.Department_Cock", "DepartmentID")
                        .WithMany()
                        .HasForeignKey("DepartmentIDDepartment_CockID");

                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");

                    b.HasOne("tbkk.Models.Supplier_Cock", "SupplierID")
                        .WithMany()
                        .HasForeignKey("SupplierIDSupplier_CockID");
                });

            modelBuilder.Entity("tbkk.Models.CarQueue", b =>
                {
                    b.HasOne("tbkk.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarQueue_CarTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.OT", "OT")
                        .WithMany()
                        .HasForeignKey("CarQueue_OTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("CarQueue_PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.CarType", b =>
                {
                    b.HasOne("tbkk.Models.CompanyCar", "CompanyCar")
                        .WithMany()
                        .HasForeignKey("CompanyCarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.Competency", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "Competency_EmployeeID")
                        .WithMany()
                        .HasForeignKey("Competency_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.GradeHistory", "Competency_GradeHistoryID")
                        .WithMany()
                        .HasForeignKey("Competency_GradeHistoryIDGradeHistoryID");
                });

            modelBuilder.Entity("tbkk.Models.DetailCarQueue", b =>
                {
                    b.HasOne("tbkk.Models.CarQueue", "CarQueue")
                        .WithMany()
                        .HasForeignKey("DetailCarQueue_CarQueueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("DetailCarQueue_EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.DetailOT", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.FoodSet", "FoodSet")
                        .WithMany()
                        .HasForeignKey("FoodSet_FoodSetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.OT", "OT")
                        .WithMany()
                        .HasForeignKey("OT_OTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("Part_PaetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.DetailOT_Cock", b =>
                {
                    b.HasOne("tbkk.Models.CarType_Cock", "CarType")
                        .WithMany()
                        .HasForeignKey("CarType_CockID");

                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");

                    b.HasOne("tbkk.Models.FoodSet_Cock", "FoodSet")
                        .WithMany()
                        .HasForeignKey("FoodSet_CockID");

                    b.HasOne("tbkk.Models.OT_Cock", "OTID")
                        .WithMany()
                        .HasForeignKey("OTIDOT_CockID");

                    b.HasOne("tbkk.Models.Part_Cock", "PartID")
                        .WithMany()
                        .HasForeignKey("PartIDPart_CockID");
                });

            modelBuilder.Entity("tbkk.Models.Employee", b =>
                {
                    b.HasOne("tbkk.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Employee_CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Employee_DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("Employee_EmployeeTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("Employee_LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tbkk.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("Employee_PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.Employee_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Company_Cock", "CompanyID")
                        .WithMany()
                        .HasForeignKey("CompanyIDCompany_CockID");

                    b.HasOne("tbkk.Models.Department_Cock", "DepartmentName")
                        .WithMany()
                        .HasForeignKey("DepartmentNameDepartment_CockID");

                    b.HasOne("tbkk.Models.EmployeeType_Cock", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeType_CockID");

                    b.HasOne("tbkk.Models.Position_Cock", "PositionID")
                        .WithMany()
                        .HasForeignKey("PositionIDPosition_CockID");
                });

            modelBuilder.Entity("tbkk.Models.FoodSet", b =>
                {
                    b.HasOne("tbkk.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("Canteen_CanteenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.GradeHistory", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "GradeHistory_EmployeeID")
                        .WithMany()
                        .HasForeignKey("GradeHistory_EmployeeIDEmployeeID");
                });

            modelBuilder.Entity("tbkk.Models.GradeHistory_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");
                });

            modelBuilder.Entity("tbkk.Models.JoinAssetEmp", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "JoinAssetEmp_AssetID")
                        .WithMany()
                        .HasForeignKey("JoinAssetEmp_AssetIDAssetID");

                    b.HasOne("tbkk.Models.Employee", "JoinAssetEmp_EmployeeID")
                        .WithMany()
                        .HasForeignKey("JoinAssetEmp_EmployeeIDEmployeeID");
                });

            modelBuilder.Entity("tbkk.Models.JoinAssetEmp_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Asset_Cock", "AssetName")
                        .WithMany()
                        .HasForeignKey("AssetNameAsset_CockID");

                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");
                });

            modelBuilder.Entity("tbkk.Models.JoinLicenseAsset", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "JoinLicenseAsset_AssetID")
                        .WithMany()
                        .HasForeignKey("JoinLicenseAsset_AssetIDAssetID");

                    b.HasOne("tbkk.Models.License", "JoinLicenseAsset_License")
                        .WithMany()
                        .HasForeignKey("JoinLicenseAsset_LicenseLicenseID");
                });

            modelBuilder.Entity("tbkk.Models.KPI", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "KPI_EmployeeID")
                        .WithMany()
                        .HasForeignKey("KPI_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.GradeHistory", "KPI_GradeHistoryID")
                        .WithMany()
                        .HasForeignKey("KPI_GradeHistoryIDGradeHistoryID");
                });

            modelBuilder.Entity("tbkk.Models.License", b =>
                {
                    b.HasOne("tbkk.Models.Company", "License_CompanyID")
                        .WithMany()
                        .HasForeignKey("License_CompanyIDCompanyID");

                    b.HasOne("tbkk.Models.Department", "License_DepartmentID")
                        .WithMany()
                        .HasForeignKey("License_DepartmentIDDepartmentID");

                    b.HasOne("tbkk.Models.Model", "License_ModelID")
                        .WithMany()
                        .HasForeignKey("License_ModelIDModelID");

                    b.HasOne("tbkk.Models.Supplier", "License_SupplierID")
                        .WithMany()
                        .HasForeignKey("License_SupplierIDSupplierID");
                });

            modelBuilder.Entity("tbkk.Models.Login", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Login_EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tbkk.Models.Model", b =>
                {
                    b.HasOne("tbkk.Models.Brand", "Model_BrandID")
                        .WithMany()
                        .HasForeignKey("Model_BrandIDBrandID");

                    b.HasOne("tbkk.Models.Category", "Model_CategoryID")
                        .WithMany()
                        .HasForeignKey("Model_CategoryIDCategoryID");
                });

            modelBuilder.Entity("tbkk.Models.Point", b =>
                {
                    b.HasOne("tbkk.Models.Part", "Point_PartID")
                        .WithMany()
                        .HasForeignKey("Point_PartIDPartID");
                });

            modelBuilder.Entity("tbkk.Models.Relationship", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "Relationship_AssetIDmom")
                        .WithMany()
                        .HasForeignKey("Relationship_AssetIDmomAssetID");

                    b.HasOne("tbkk.Models.Asset", "Relationship_AssetIDson")
                        .WithMany()
                        .HasForeignKey("Relationship_AssetIDsonAssetID");
                });

            modelBuilder.Entity("tbkk.Models.Repair", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "Repair_AssetID")
                        .WithMany()
                        .HasForeignKey("Repair_AssetIDAssetID");

                    b.HasOne("tbkk.Models.Employee", "Repair_EmployeeID")
                        .WithMany()
                        .HasForeignKey("Repair_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.Report", "Repair_ReportID")
                        .WithMany()
                        .HasForeignKey("Repair_ReportIDReportID");
                });

            modelBuilder.Entity("tbkk.Models.Repair_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Asset_Cock", "AssetID")
                        .WithMany()
                        .HasForeignKey("AssetIDAsset_CockID");

                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");

                    b.HasOne("tbkk.Models.Report_Cock", "ReportID")
                        .WithMany()
                        .HasForeignKey("ReportIDReport_CockID");
                });

            modelBuilder.Entity("tbkk.Models.Report", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "Report_AssetID")
                        .WithMany()
                        .HasForeignKey("Report_AssetIDAssetID");

                    b.HasOne("tbkk.Models.Employee", "Report_EmployeeID")
                        .WithMany()
                        .HasForeignKey("Report_EmployeeIDEmployeeID");
                });

            modelBuilder.Entity("tbkk.Models.Report_Cock", b =>
                {
                    b.HasOne("tbkk.Models.Asset_Cock", "AssetID")
                        .WithMany()
                        .HasForeignKey("AssetIDAsset_CockID");

                    b.HasOne("tbkk.Models.Employee_Cock", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDEmployee_CockID");
                });

            modelBuilder.Entity("tbkk.Models.Suggestion", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "Suggestion_EmployeeID")
                        .WithMany()
                        .HasForeignKey("Suggestion_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.GradeHistory", "Suggestion_GradeHistoryID")
                        .WithMany()
                        .HasForeignKey("Suggestion_GradeHistoryIDGradeHistoryID");
                });

            modelBuilder.Entity("tbkk.Models.UpdateAsset", b =>
                {
                    b.HasOne("tbkk.Models.Asset", "UpdateAsset_AssetID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_AssetIDAssetID");

                    b.HasOne("tbkk.Models.Company", "UpdateAsset_CompanyID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_CompanyIDCompanyID");

                    b.HasOne("tbkk.Models.Employee", "UpdateAsset_EmployeeID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.Location", "UpdateAsset_LocationID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_LocationIDLocationID");

                    b.HasOne("tbkk.Models.Model", "UpdateAsset_ModelID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_ModelIDModelID");

                    b.HasOne("tbkk.Models.Department", "UpdateAsset_SepartmentID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_SepartmentIDDepartmentID");

                    b.HasOne("tbkk.Models.Supplier", "UpdateAsset_SupplierID")
                        .WithMany()
                        .HasForeignKey("UpdateAsset_SupplierIDSupplierID");
                });

            modelBuilder.Entity("tbkk.Models.UpdateLicense", b =>
                {
                    b.HasOne("tbkk.Models.Company", "UpdateLicense_CompanyID")
                        .WithMany()
                        .HasForeignKey("UpdateLicense_CompanyIDCompanyID");

                    b.HasOne("tbkk.Models.Department", "UpdateLicense_DepartmentID")
                        .WithMany()
                        .HasForeignKey("UpdateLicense_DepartmentIDDepartmentID");

                    b.HasOne("tbkk.Models.License", "UpdateLicense_LicenseID")
                        .WithMany()
                        .HasForeignKey("UpdateLicense_LicenseIDLicenseID");

                    b.HasOne("tbkk.Models.Model", "UpdateLicense_ModelID")
                        .WithMany()
                        .HasForeignKey("UpdateLicense_ModelIDModelID");

                    b.HasOne("tbkk.Models.Supplier", "UpdateLicense_SupplierID")
                        .WithMany()
                        .HasForeignKey("UpdateLicense_SupplierIDSupplierID");
                });

            modelBuilder.Entity("tbkk.Models.UpdateNetwork", b =>
                {
                    b.HasOne("tbkk.Models.Employee", "UpdateNetwork_EmployeeID")
                        .WithMany()
                        .HasForeignKey("UpdateNetwork_EmployeeIDEmployeeID");

                    b.HasOne("tbkk.Models.Network", "UpdateNetwork_NetworkID")
                        .WithMany()
                        .HasForeignKey("UpdateNetwork_NetworkIDNetworkID");
                });
#pragma warning restore 612, 618
        }
    }
}
